### ISSUE TITLE
Stuck at Building process 

### ISSUE THREAD

**Issue by Lyndonxie** [aviks/Taro.jl#50] opened 2019-05-06 14:20 UTC
julia1.1
(v1.1) pkg> add Taro
  Updating registry at `C:\Users\Administrator\.julia\registries\General`
┌ Warning: Some registries failed to update:
│     — `C:\Users\Administrator\.julia\registries\General` — registry dirty
└ @ Pkg.Types C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Types.jl:1269
 Resolving package versions...
 Installed Taro ─ v0.7.0
  Updating `C:\Users\Administrator\.julia\environments\v1.1\Project.toml`
  [61d0e4fa] + Taro v0.7.0
  Updating `C:\Users\Administrator\.julia\environments\v1.1\Manifest.toml`
  [61d0e4fa] + Taro v0.7.0
  ****Building Taro → `C:\Users\Administrator\.julia\packages\Taro\0trbq\deps\build.log`****

**Comment by MichaeLeroy** [comment] 2019-06-16 23:35
I had a similar problem.  My issue with building was caused by a new version of an external dependency, Apache tika.  I made a PR to fix my issue, #51.  Perhaps when and if this PR is accepted and makes it into the registry, your issue will disappear.

**Comment by ljschumacher** [comment] 2019-07-31 14:47
I encountered the same problem
`┌ Error: Error building `Taro`: 
│   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
│                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
│ curl: (22) The requested URL returned error: 404 Not Found
│ [ Info:   Downloading tika-app-1.20.jar from Apache OSUOSL Mirror
...`

**Comment by bjarthur** [comment] 2019-08-01 12:58
worth noting that java is broken on julia 1.1 and won't be fixed by 1.2.  see https://github.com/JuliaLang/julia/issues/31104.  a pure julia alternative to taro.jl is https://github.com/felipenoris/XLSX.jl.

**Comment by aviks** [comment] 2020-02-14 11:10
The Taro build process is now fixed, and JavaCall works in Julia 1.3. It continues to work on our LTS version 1.0. Sorry for the slow response, I'd missed seeing the updates here.

**Closed by aviks** 2020-02-14 11:10 UTC
